export const AttendanceActions = {
  PUNCH_IN: 'PUNCH_IN',
  PUNCH_OUT: 'PUNCH_OUT',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_TODAY_ATTENDANCE: 'SET_TODAY_ATTENDANCE',
  SET_CALENDAR_ATTENDANCE: 'SET_CALENDAR_ATTENDANCE',
};
