export const AIChatActions = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  ADD_MESSAGE: 'ADD_MESSAGE',
  SET_AI_RESPONSE: 'SET_AI_RESPONSE',
  START_AI_STREAMING: 'START_AI_STREAMING',
  APPEND_AI_TEXT: 'APPEND_AI_TEXT',
  FINISH_AI_STREAMING: 'FINISH_AI_STREAMING',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  RESET: 'RESET',
};
