export const LeaveActions = {
    SET_LOADING: 'SET_LOADING',
    SET_REQUESTS_LOADING: 'SET_REQUESTS_LOADING',
    SET_APPLY_LOADING: 'SET_APPLY_LOADING',
    SET_BALANCE_LOADING: 'SET_BALANCE_LOADING',
    SET_ERROR: 'SET_ERROR',
    SET_LEAVE: 'SET_LEAVE',
    SET_LEAVE_APPLY: 'SET_LEAVE_APPLY',
    SET_LEAVE_REQUESTS: 'SET_LEAVE_REQUESTS',
    SET_LEAVE_BALANCE: 'SET_LEAVE_BALANCE',
  };
  