export const TaskActions = {
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_TASKS: 'SET_TASKS',
  SET_DETAIL_LOADING: 'SET_DETAIL_LOADING',
  SET_TASK_DETAIL: 'SET_TASK_DETAIL',
  SET_DETAIL_ERROR: 'SET_DETAIL_ERROR',
  SET_STATUS_UPDATING: 'SET_STATUS_UPDATING',
  CLEAR_TASK_DETAIL: 'CLEAR_TASK_DETAIL',
};
